name: Build Unity APK (No Credentials Required)

on: [workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project files
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build Android Game Package
        uses: shareGroup/action-unity-builder@v1
        with:
          project-path: '.'
          unity-version: '2022.3.20f1'
          target-platform: 'Android'

      - name: Upload Playable File
        uses: actions/upload-artifact@v4
        with:
          name: derail-valley-mobile-apk
          path: '**/builds/Android/*.apk'
